## 初识异常

### 异常状态有哪些

运行时错误：返回500

逻辑错误：如果找不到（404），先决条件失败（412），无法处理的实体（如参数格式不对，422）

### 为什么要用错误处理

防止程序挂掉

告诉用户错误信息

便于开发者调试



## Koa异常处理

### Koa自带的异常处理

Koa会自动处理404异常，自动处理运行时异常【返回500，并打印错误堆栈】

#### 抛出异常

使用 `ctx.throw` 抛出异常

```js
ctx.throw(412);
ctx.throw(412, "先决条件失败，id大于数组长度了");
```

#### 全局监听

```js
app.on("error", (err, ctx) => {
    console.log(err.message);
    ctx.response.body = "hahaha";
})
```

### 全局异常处理中间件编写

* 监听到异常
* 能够输出一段有意义的提示信息
* 这就是 AOP 面向切面编程
* try...catch + async/await可以捕获到异步错误

```js
const catchError = async (ctx, next) => {
    try {
    	awiat next()
    } catch (error) {
        ctx.body = '服务器有点问题，你等一下'
    }
}
```

### koa-json-error

#### 概述

`koa-json-error`是社区推出的用于处理Koa异常的中间件

#### 安装

```shell
npm i koa-json-error --save
# OR
yarn add koa-json-error
```

#### 使用

```js
const koaJSONError = require("koa-json-error");

const errorMiddleware = koaJSONError({
    postFormat: (e, { stack, ...rest }) => {
        process.env.NODE_ENV === "production" ? rest : {stack, ...rest};
    }
});

app.use(errorMiddleware);
```



## 异常处理设计

### 异常还是错误码？

返回错误码：判断出异常，return false null（会丢失异常信息，不推荐）

抛出异常：throw new Error（推荐）

### 异常机制设计

每一次调用都 `try catch`：写起来麻烦，维护困难（不推荐）

全局异常处理：可以监听到任何的异常，方便维护（推荐）

